spring:
  http:
    encoding:
      charset: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.10.81:3306/auxiliaryPlatform?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
hr:
  driverCLass: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@172.30.10.113:1521:orcl
  username: yksoft
  password: yksoft1919